### ISSUE TITLE
Firebase V9 compatibility

### ISSUE THREAD

**Issue by tiffanynk** [SimCoderYoutube/TiktokClone#17]
`import firebase from "firebase/app"` threw an error saying:

`export 'default' (imported as 'firebase') was not found in 'firebase/app'`

Solved by changing imports to:
```
import firebase from 'firebase/compat/app';
import 'firebase/compat/auth';
import 'firebase/compat/firestore';
```

**Comment by SimCoderYoutube** [comment]
The project is running version v8 of firebase, if you want to use v9 you'll have to use compact, I do intend on updating this in the near future.
